# Generated by Django 2.2 on 2019-05-17 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wasteweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AngkutanTrukSampah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_angkutan_truk', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='inputop',
            name='nama_angkutan',
        ),
        migrations.AddField(
            model_name='inputop',
            name='nama_angkutan_truk',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='wasteweb.AngkutanTrukSampah'),
            preserve_default=False,
        ),
    ]
