# Generated by Django 2.2 on 2019-05-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasteweb', '0002_auto_20190518_0101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AngkutanSampah',
        ),
    ]
