# Generated by Django 2.2 on 2019-05-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasteweb', '0005_auto_20190518_0132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InputOP',
        ),
    ]
