# Generated by Django 2.2 on 2019-05-17 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wasteweb', '0006_delete_inputop'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(max_length=100)),
                ('jam', models.TimeField(max_length=100)),
                ('jumlah', models.IntegerField()),
                ('nama_angkutan_truk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasteweb.AngkutanTrukSampah')),
                ('nama_lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasteweb.LokasiKecamatan')),
                ('nama_sampah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasteweb.Sampah')),
            ],
        ),
        migrations.DeleteModel(
            name='InputanOP',
        ),
    ]
